---
- name: install
  become: yes
  dnf:
    name: chrony
    state: latest

- name: config
  copy:
    src: chrony.conf
    dest: /etc

- name: enable
  become: yes
  systemd:
    name: chronyd.service
    state: restarted
    enabled: yes